### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by cajeiri** [jaumeortola/hyphen-ca#5]
Sorry for the weird question, but how does your hyphenation pattern compare to the one [here](https://github.com/hyphenation/tex-hyphen/blob/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-ca.tex)?

**Comment by jaumeortola** [comment]
The testing does a comparison with the patterns you mention. 
See https://github.com/jaumeortola/hyphen-ca/blob/master/resum-resultats.txt

2418 errors are removed in the list of word collected by me (from dictionaries and problematic words found by collaborators).
